config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'user_sessions#new'

  resources :alunos, :circulares, :clientes, :cursos, :despesas, :horarios, :lecionam, :professores, :salarios, :tipificacoes, :users, :user_sessions

  #users and sessions
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'
  get 'index' => 'user_sessions#index'
  get 'validate_user/:id', to: "users#validate_user", as: :validate_user

  #alunos
  get 'aluno/busca_dados_cliente', to: "alunos#busca_dados_cliente"
  get 'alunos_inativos', to: "alunos#inativos"
  get 'alterna_aluno/:id', to: "alunos#alterna_aluno", as: :alterna_aluno

  #circulares
  post 'circular_vigente', to: "circulares#circular_vigente"

  #clientes
	get 'alterna_cliente/:id', to: "clientes#alterna_cliente", as: :alterna_cliente
  get 'clientes_inativos', to: "clientes#inativos"
  get 'email_clientes', to: "clientes#listar_emails"

  #financas
  get 'visualiza_boletos', to: "financas#visualiza_boletos"
  get 'visualiza_folha', to: "financas#visualiza_folha"

  #horarios
  get 'horario/:professor_id/disponivel' => 'horarios#new', as: :disponivel
  get 'horario/:professor_id' => 'horarios#destroy_all',  as: :destroy_all

  #lecionam
  get 'lecionam/:curso_id/lecionar' => 'lecionam#new', as: :lecionar

  #matriculas
  resources :matriculas do
    collection do
      get 'busca_professores', to: "matriculas#busca_professores"
      get 'busca_horarios', to: "matriculas#busca_horarios"
      get 'busca_horarios_teoria', to: "matriculas#busca_horarios_teoria"
      get 'busca_dados_curso', to: "matriculas#busca_dados_curso"
      get 'tipo_teoria', to: "matriculas#tipo_teoria"
    end
  end
  get 'matricula_nova', to: "matriculas#new"
  get 'reimprimir_contratos', to: "matriculas#reimprimir_contratos"
  get 'matricula_extra', to: "matriculas#new"
  get 'matriculas_encerradas', to: "matriculas#encerradas"
  get 'altera_encerramento', to: "matriculas#altera_encerramento"
  post 'refaz_contrato', to: "matriculas#refaz_contrato"
  get 'rematricular', to: "matriculas#rematricular"
  get 'rematricular_base', to: "matriculas#rematricular_base"
  get 'reativar_matricula/:id', to: "matriculas#reativar_matricula", as: :reativar_matricula

  #professores
  get 'professores_inativos', to: "professores#inativos"
  get 'professor/:id/controlar_horarios' => 'professores#controlar_horarios', as: :controlar_horarios
  get 'professor/:id/listar_alunos' => 'professores#listar_alunos', as: :listar_alunos
  get 'professor/:horario_id/alunos_horario' => 'professores#alunos_horario', as: :alunos_horario
  get 'alterna_professor/:id', to: "professores#alterna_professor", as: :alterna_professor

  #salarios
  get 'atribuir_salarios', to: "salarios#atribuir_salarios"
  get 'salarios/:professor_id/visualizar_salarios', to: 'salarios#visualizar_salarios', as: :visualizar_salarios

end

app/models/cliente.rb
class Cliente < ApplicationRecord
	#associações no banco de dados
  has_many :alunos

  #validações
  validates :cpf,:rg, :uniqueness => { :scope => :ativo }
  validates :nome, :endereco, :rg, :cpf, :telefone, :celular, :email, :nascimento, :bairro, :cidade, :uf,
  :cep, :pai, :mae, :nacionalidade, :profissao, presence: true

  def nome=(s)
    super s.titleize
  end

  def endereco=(s)
    super s.titleize
  end

  def bairro=(s)
    super s.titleize
  end

  def cidade=(s)
    super s.titleize
  end

  def uf=(s)
    super s.upcase
  end

  def pai=(s)
    super s.titleize
  end

  def mae=(s)
    super s.titleize
  end

  def nacionalidade=(s)
    super s.titleize
  end

  def profissao=(s)
    super s.titleize
  end
end

app/controllers/clientes_controller.rb
# coding: utf-8
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy, :alterna_cliente]

  def index
    @clientes_total = Cliente.where(ativo: true)
    @pagy, @clientes = pagy(@clientes_total.order(:id))
  end

  def show
    @alunos = Aluno.where(cliente_id: params[:id]).order(:id)
  end

  def new
    @cliente = Cliente.new
  end

  def edit
  end

  def create
    @cliente = Cliente.new(cliente_params)
    @cliente.ativo = true
    respond_to do |format|
      if @cliente.save
        #gera_notificacao("admin",@cliente, action_name)
        format.html { redirect_to @cliente, notice: "Cliente #{@cliente.nome} criado com sucesso." }
        #format.json { render action: 'show', status: :created, location: @cliente }
      else
        showErrors(@cliente.errors)
        format.html { render action: 'new' }
        #format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        #gera_notificacao("admin",@cliente, action_name)
        format.html { redirect_to @cliente, notice: "Dados do cliente #{@cliente.nome} foram atualizados com sucesso." }
        #format.json { head :no_content }
      else
        showErrors(@cliente.errors)
        format.html { render action: 'edit' }
        #format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @cliente.alunos.any?
      redirect_to clientes_path, alert: "Não foi possível excluir o(a) cliente #{@cliente.nome}. Primeiro você precisa excluir os alunos vinculadas."
    else
      respond_to do |format|
        if @cliente.destroy
          #gera_notificacao("admin",@cliente, action_name)
          format.html { redirect_to clientes_path}
          #format.json { head :no_content }
        else
          showErrors(@cliente.errors)
          format.html { redirect_back fallback_location: clientes_path }
        end
      end
    end
  end

  def inativos
    @inativos = Cliente.where(ativo: false)
    @pagy, @clientes = pagy(@inativos.order(:id))
  end

  def alterna_cliente
    if @cliente.ativo?
      if @cliente.alunos.any?
        redirect_to clientes_path, alert: "Não foi possível desativar o(a) cliente #{@cliente.nome}, pois existem alunos vinculados a ele(a)."
        return
      else  
        @cliente.update_attribute(:ativo, false)
        redirect_to clientes_path, notice: "Cliente #{@cliente.nome} desativado com sucesso."
      end
    else
      @cliente.update_attribute(:ativo, true)
      redirect_to clientes_inativos_path, notice: "Cliente #{@cliente.nome} reativado com sucesso."
    end
  end

  def listar_emails
    @emails = ""
    @email_ausente = []
    @clientes = Cliente.all
    @clientes.each do |cliente|
      cliente.alunos.each do |aluno|
        if aluno.matriculas.size > 0
          unless cliente.email == "@"
            @emails << "#{cliente.email};"
          else
            @email_ausente << cliente.nome
          end
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :endereco, :rg, :cpf, :telefone, :celular, :email, :nascimento, :bairro, :cidade,
        :uf, :cep, :pai, :mae, :nacionalidade, :profissao)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_alunos_vinculados.html.erb
<table class="table table-striped">
  
  <thead>
    <tr>
      <th>Alunos Vinculados</th>
      <th>Curso</th>
      <th>Valor Mensal</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% if @alunos.size > 0 %>
    <% valor_total = 0 %>
    <% @alunos.each do |aluno| %>
      <% if aluno.matriculas.size > 0 %>
        <% aluno.matriculas.each do |matricula| %>
          <tr>
            <td><%= aluno.nome %></td>
            <td><%= matricula.curso.nome %></td>
            <td><%= number_to_currency(matricula.valor_mensal) %></td><% valor_total = valor_total + matricula.valor_mensal %>
            <td><%= button_to 'Abrir Ficha', aluno_path(aluno), :class => "btn btn-primary btn-xs", :method => :get %>
            <%= button_to 'Editar Dados', edit_aluno_path(aluno), :class => "btn btn-primary btn-xs", :method => :get %>
            <%= button_to 'Excluir', aluno, :class => "btn btn-primary btn-xs", :method => :delete, data: { confirm: "Tem certeza que deseja excluir o aluno #{aluno.nome}?" } %></td>
          </tr>
        <% end %>
      <% else %> 
        <tr>
          <td><%= aluno.nome %></td>
          <td>Aluno não está matriculado em cursos.</td>
          <td>R$ 0,00</td>
          <td>
            <%= link_to aluno, :class => "btn btn-primary btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
                  <span class="text">Abrir</span>
                <% end %>
                <%= link_to edit_aluno_path(aluno), :class => "btn btn-warning btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-exclamation-triangle"></i></span>
                  <span class="text">Editar</span>
                <% end %>
                <%= link_to alterna_aluno_path(aluno), :class => "btn btn-danger btn-icon-split btn-sm", :method => :get, data: { confirm: "Tem certeza que deseja alterar o status do(a) aluno(a) #{aluno.nome}?" } do %>
                  <span class="icon text-white-50"><i class="fas fa-trash"></i></span>
                  <span class="text"><%= aluno.ativo ? 'Desativar' : 'Ativar' %></span>
                <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <tr>
      <td><b>Mensalidade Total: <%= number_to_currency(valor_total) %></b></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  <% else %>
    <tr>
      <td>Nenhum aluno vinculado ao cliente.</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/clientes/_form.html.erb
<div class="container">
  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-12">
          <div class="p-5">
            <%= form_with model: @cliente, local: true, class: "user" do |f| %>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nome', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'CPF', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :nome, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :cpf, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Endereço', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 text-center">
                  <%= f.label 'Bairro', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :endereco, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :bairro, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Cidade', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Estado', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6  mb-3 mb-sm-0">
                  <%= f.text_field :cidade, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :uf, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'CEP', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Email', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">            
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :cep, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :email, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Telefone', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Celular', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :telefone, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :celular, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'RG', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Data de Nascimento', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :rg, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <% if action_name != "edit" %>
                    <%= f.text_field :nascimento, class: "form-control" %>
                  <% else %>
                    <%= f.text_field :nascimento, class: "form-control", value: @cliente.nascimento.datePTBR %>
                  <% end %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nacionalidade', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nome do Pai', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :nacionalidade, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :pai, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nome da Mãe', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Profissão', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :mae, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :profissao, class: "form-control" %>
                </div>
              </div>
              <%= f.submit "Salvar", class: "btn btn-primary btn-user btn-block" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clientes/edit.html.erb
<%= render 'form' %>

app/views/clientes/inativos.html.erb
<!-- Table -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= controller_name.capitalize %> Inativos <small>// Quantidade: <%= @inativos.size %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="userTable" width="100%" cellspacing="0">
        <thead>
          <tr role="row">
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 3%;">Nº</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 34%;">Nome</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 15%;">Telefone</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 15%;">Celular</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 33%;">Opções</th>
          </tr>
       </thead>

       <tbody>
       		<% @clientes.each do |cliente| %>
			      <tr>
              <td><%= cliente.id %></td>
			        <td><%= cliente.nome %></td>
			        <td><%= cliente.telefone %></td>
			        <td><%= cliente.celular %></td>
              <td>
                <%= link_to cliente, :class => "btn btn-primary btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
                  <span class="text">Abrir</span>
                <% end %>
                <%= link_to edit_cliente_path(cliente), :class => "btn btn-warning btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-exclamation-triangle"></i></span>
                  <span class="text">Editar</span>
                <% end %>
                <%= link_to alterna_cliente_path(cliente), :class => "btn btn-danger btn-icon-split btn-sm", :method => :get, data: { confirm: "Tem certeza que deseja reativar o(a) #{controller_name.singularize} #{cliente.nome}?" } do %>
                  <span class="icon text-white-50"><i class="fas fa-trash"></i></span>
                  <span class="text">Reativar</span>
                <% end %>
              </td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
    <%== pagy_bootstrap_nav(@pagy) %>
	</div>
</div>
<!-- End of Table -->

app/views/clientes/index.html.erb
<!-- Table -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= controller_name.capitalize %> Cadastrados(as) <small>// Quantidade: <%= @clientes_total.size %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="userTable" width="100%" cellspacing="0">
        <thead>
          <tr role="row">
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 3%;">Nº</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 34%;">Nome</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 15%;">Telefone</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 15%;">Celular</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 33%;">Opções</th>
          </tr>
       </thead>

       <tbody>
       		<% @clientes.each do |cliente| %>
			      <tr>
              <td><%= cliente.id %></td>
			        <td><%= cliente.nome %></td>
			        <td><%= cliente.telefone %></td>
			        <td><%= cliente.celular %></td>
              <td>
                <%= link_to cliente, :class => "btn btn-primary btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
                  <span class="text">Abrir</span>
                <% end %>
                <%= link_to edit_cliente_path(cliente), :class => "btn btn-warning btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-exclamation-triangle"></i></span>
                  <span class="text">Editar</span>
                <% end %>
                <%= link_to alterna_cliente_path(cliente), :class => "btn btn-danger btn-icon-split btn-sm", :method => :get, data: { confirm: "Tem certeza que deseja desativar o(a) #{controller_name.singularize} #{cliente.nome}?" } do %>
                  <span class="icon text-white-50"><i class="fas fa-trash"></i></span>
                  <span class="text">Desativar</span>
                <% end %>
              </td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
    <%== pagy_bootstrap_nav(@pagy) %>
	</div>
</div>
<!-- End of Table -->

app/views/clientes/new.html.erb
<%= render 'form' %>

app/views/clientes/show.erb
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary"><%= @cliente.nome %> - Status: <u><%= @cliente.ativo ? 'Ativo' : 'Inativo' %></u></h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Ações:</div>
        <%= link_to "Editar dados", edit_cliente_path(@cliente), class: "dropdown-item" %>
        <%= link_to "Alterar status", alterna_cliente_path(@cliente), { class: "dropdown-item", data: { confirm: "Tem certeza que deseja alterar o status do(a) #{controller_name.singularize} #{@cliente.nome}?" }} %>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
  	<div class="form-group row">
  	<div class="col-sm-6 mb-3 mb-sm-0">
     	<ul class="list-group">
	      <li class="list-group-item"><b>Cliente nº:</b> <%= @cliente.id %></li>
	      <li class="list-group-item"><b>Endereço:</b> <%= @cliente.endereco %></li>
	      <li class="list-group-item"><b>Cidade:</b> <%= @cliente.cidade %></li>
	      <li class="list-group-item"><b>CEP:</b> <%= @cliente.cep %></li>
	      <li class="list-group-item"><b>Telefone:</b> <%= @cliente.telefone %></li>
	      <li class="list-group-item"><b>RG:</b> <%= @cliente.rg %></li>
	      <li class="list-group-item"><b>Nome da Mãe:</b> <%= @cliente.mae %></li>
	      <li class="list-group-item"><b>Nacionalidade:</b> <%= @cliente.nacionalidade %></li>
	    </ul>
	  </div>
	  <div class="col-sm-6">
	    <ul class="list-group">
	      <li class="list-group-item"><b>CPF:</b> <%= @cliente.cpf %></li>
	      <li class="list-group-item"><b>Bairro:</b> <%= @cliente.bairro %></li>
	      <li class="list-group-item"><b>Estado:</b> <%= @cliente.uf %></li>
	      <li class="list-group-item"><b>E-mail:</b> <%= @cliente.email %></li>
	      <li class="list-group-item"><b>Celular:</b> <%= @cliente.celular %></li>
	      <li class="list-group-item"><b>Nascimento:</b> <%= @cliente.nascimento.datePTBR %></li>
	      <li class="list-group-item"><b>Nome do Pai:</b> <%= @cliente.pai %></li>
	      <li class="list-group-item"><b>Profissão:</b> <%= @cliente.profissao %></li>
	    </ul>
	  </div>
	</div>
	
	<%= render 'alunos_vinculados' %>
</div>