config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'user_sessions#new'

  resources :alunos, :circulares, :clientes, :cursos, :despesas, :horarios, :lecionam, :professores, :salarios, :tipificacoes, :users, :user_sessions

  #users and sessions
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'
  get 'index' => 'user_sessions#index'
  get 'validate_user/:id', to: "users#validate_user", as: :validate_user

  #alunos
  get 'aluno/busca_dados_cliente', to: "alunos#busca_dados_cliente"
  get 'alunos_inativos', to: "alunos#inativos"
  get 'alterna_aluno/:id', to: "alunos#alterna_aluno", as: :alterna_aluno

  #circulares
  post 'circular_vigente', to: "circulares#circular_vigente"

  #clientes
	get 'alterna_cliente/:id', to: "clientes#alterna_cliente", as: :alterna_cliente
  get 'clientes_inativos', to: "clientes#inativos"
  get 'email_clientes', to: "clientes#listar_emails"

  #financas
  get 'visualiza_boletos', to: "financas#visualiza_boletos"
  get 'visualiza_folha', to: "financas#visualiza_folha"

  #horarios
  get 'horario/:professor_id/disponivel' => 'horarios#new', as: :disponivel
  get 'horario/:professor_id' => 'horarios#destroy_all',  as: :destroy_all

  #lecionam
  get 'lecionam/:curso_id/lecionar' => 'lecionam#new', as: :lecionar

  #matriculas
  resources :matriculas do
    collection do
      get 'busca_professores', to: "matriculas#busca_professores"
      get 'busca_horarios', to: "matriculas#busca_horarios"
      get 'busca_horarios_teoria', to: "matriculas#busca_horarios_teoria"
      get 'busca_dados_curso', to: "matriculas#busca_dados_curso"
      get 'tipo_teoria', to: "matriculas#tipo_teoria"
    end
  end
  get 'matricula_nova', to: "matriculas#new"
  get 'reimprimir_contratos', to: "matriculas#reimprimir_contratos"
  get 'matricula_extra', to: "matriculas#new"
  get 'matriculas_encerradas', to: "matriculas#encerradas"
  get 'altera_encerramento', to: "matriculas#altera_encerramento"
  post 'refaz_contrato', to: "matriculas#refaz_contrato"
  get 'rematricular', to: "matriculas#rematricular"
  get 'rematricular_base', to: "matriculas#rematricular_base"
  get 'reativar_matricula/:id', to: "matriculas#reativar_matricula", as: :reativar_matricula

  #professores
  get 'professores_inativos', to: "professores#inativos"
  get 'professor/:id/controlar_horarios' => 'professores#controlar_horarios', as: :controlar_horarios
  get 'professor/:id/listar_alunos' => 'professores#listar_alunos', as: :listar_alunos
  get 'professor/:horario_id/alunos_horario' => 'professores#alunos_horario', as: :alunos_horario
  get 'alterna_professor/:id', to: "professores#alterna_professor", as: :alterna_professor

  #salarios
  get 'atribuir_salarios', to: "salarios#atribuir_salarios"
  get 'salarios/:professor_id/visualizar_salarios', to: 'salarios#visualizar_salarios', as: :visualizar_salarios

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 6 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :name, presence: true
  validates :level, presence: true
  validates :email, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, except: [:new, :create, :index]
  before_action :admin_level_check, only: [:validate_user, :admin_update, :destroy, :index]
	skip_before_action :require_login, only: [:new, :create]

	def index
    @users_total = User.order(:id)
    @pagy, @users = pagy(@users_total)
  end

  def new
		@user = User.new
	end

	# POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if User.all.size < 1
    	@user.level = "admin"
    elsif @user.level.nil?
      @user.level = "pending"
    end
    respond_to do |format|
      if @user.save
        if logged_in?
          format.html { redirect_to users_path, notice: "Usuário #{@user.name} cadastrado com sucesso." }
        else 
          format.html { redirect_to root_path, notice: "Usuário #{@user.name} cadastrado com sucesso." }
        end
        #format.json { render action: 'show', status: :created, location: @user }
      else
        showErrors(@user.errors)
        format.html { render :new }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def show
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: "O cadastro do usuário #{@user.name} foi atualizado com sucesso." }
        #format.json { head :no_content }
      else
        showErrors(@user.errors)
        format.html { render :edit }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        if User.all.size < 1
          logout
        end
          format.html { redirect_to users_path }
          #format.json { head :no_content }
      else
        showErrors(@user.errors)
        format.html { redirect_back fallback_location: users_path }
      end
    end
  end

  def admin_update
  end

  def validate_user
    if @user.update_attribute(:level, 'user')
      respond_to do |format|
        format.html { redirect_to users_path, notice: "Usuário #{@user.name} validado com sucesso." }
        #format.json {}
      end
    else
      redirect_to users_path, alert: "#{@user.errors.full_messages}"
    end
  end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :level)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<div class="container">
  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <%= form_with model: @user, local: true, class: "user" do |f| %>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Email', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nome', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :email, class: "form-control form-control-user", placeholder: "Endereço de Email" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :name, class: "form-control form-control-user", placeholder: "Nome" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Senha', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Confirmação da senha', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.password_field :password, class: "form-control form-control-user", placeholder: "Senha" %>
                </div>
                <div class="col-sm-6">
                  <%= f.password_field :password_confirmation, class: "form-control form-control-user", placeholder: "Repetir Senha" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-12 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nível de Usuário', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-12 mb-3 mb-sm-0">
                  <%= f.select :level, get_config("chvl_user_roles"), {}, class: "form-control" %>
                </div>
              </div>
                <%= f.submit "Salvar Dados", class: "btn btn-primary btn-user btn-block" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="container">
  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">Crie uma conta!</h1>
            </div>
            <%= form_with model: @user, local: true, class: "user" do |f| %>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :email, class: "form-control form-control-user", placeholder: "Endereço de Email" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :name, class: "form-control form-control-user", placeholder: "Nome" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.password_field :password, class: "form-control form-control-user", placeholder: "Senha" %>
                </div>
                <div class="col-sm-6">
                  <%= f.password_field :password_confirmation, class: "form-control form-control-user", placeholder: "Repetir Senha" %>
                </div>
              </div>
              <% if logged_in? && current_user.is_admin? %>
                <div class="form-group row">
                  <div class="col-sm-12 mb-3 mb-sm-0">
                    <%= f.select :level, get_config("chvl_user_roles"), {}, class: "form-control" %>
                  </div>
                </div>
              <% end %>
              <%= f.submit "Criar Conta", class: "btn btn-primary btn-user btn-block" %>
            <% end %>
            <% unless logged_in? %>
              <hr>
              <div class="text-center">
                <%= link_to "Já tem cadastro?", root_path, :class => "small" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'edit_form' %>

app/views/users/index.html.erb
<!-- Table -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Usuários Cadastrados <small>// Quantidade: <%= @users_total.size %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="userTable" width="100%" cellspacing="0">
        <thead>
          <tr role="row">
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 3%;">id</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 35%;">Email</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 30%;">Nome</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 10%;">Nível</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 21%;">Opções</th>
          </tr>
       </thead>

       <tbody>
       		<% @users.each do |user| %>
			      <tr>
              <td><%= user.id %></td>
			        <td><%= user.email %></td>
			        <td><%= user.name %></td>
			        <td><%= user.level %></td>
              <td>
                <% if user.is_pending? %>
                  <%= link_to validate_user_path(user), :class => "btn btn-success btn-icon-split btn-sm", :method => :get, data: { confirm: "Tem certeza que deseja validar o usuário #{user.name}?" } do %>
                      <span class="icon text-white-50"><i class="fas fa-check"></i></span>
                      <span class="text">Validar</span>
                  <% end %>
                <% else %>
                  <%= link_to edit_user_path(user), :class => "btn btn-warning btn-icon-split btn-sm", :method => :get do %>
                    <span class="icon text-white-50"><i class="fas fa-exclamation-triangle"></i></span>
                    <span class="text">Editar</span>
                  <% end %>
                <% end %>
                <%= link_to user, :class => "btn btn-danger btn-icon-split btn-sm", :method => :delete, data: { confirm: "Tem certeza que deseja excluir o usuário #{user.name}?" } do %>
                  <span class="icon text-white-50"><i class="fas fa-trash"></i></span>
                  <span class="text">Excluir</span>
                <% end %>
              </td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
    <%== pagy_bootstrap_nav(@pagy) %>
	</div>
</div>
<!-- End of Table -->

app/views/users/new.html.erb
<%= render 'form' %>