config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'user_sessions#new'

  resources :alunos, :circulares, :clientes, :cursos, :despesas, :horarios, :lecionam, :professores, :salarios, :tipificacoes, :users, :user_sessions

  #users and sessions
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'
  get 'index' => 'user_sessions#index'
  get 'validate_user/:id', to: "users#validate_user", as: :validate_user

  #alunos
  get 'aluno/busca_dados_cliente', to: "alunos#busca_dados_cliente"
  get 'alunos_inativos', to: "alunos#inativos"
  get 'alterna_aluno/:id', to: "alunos#alterna_aluno", as: :alterna_aluno

  #circulares
  post 'circular_vigente', to: "circulares#circular_vigente"

  #clientes
	get 'alterna_cliente/:id', to: "clientes#alterna_cliente", as: :alterna_cliente
  get 'clientes_inativos', to: "clientes#inativos"
  get 'email_clientes', to: "clientes#listar_emails"

  #financas
  get 'visualiza_boletos', to: "financas#visualiza_boletos"
  get 'visualiza_folha', to: "financas#visualiza_folha"

  #horarios
  get 'horario/:professor_id/disponivel' => 'horarios#new', as: :disponivel
  get 'horario/:professor_id' => 'horarios#destroy_all',  as: :destroy_all

  #lecionam
  get 'lecionam/:curso_id/lecionar' => 'lecionam#new', as: :lecionar

  #matriculas
  resources :matriculas do
    collection do
      get 'busca_professores', to: "matriculas#busca_professores"
      get 'busca_horarios', to: "matriculas#busca_horarios"
      get 'busca_horarios_teoria', to: "matriculas#busca_horarios_teoria"
      get 'busca_dados_curso', to: "matriculas#busca_dados_curso"
      get 'tipo_teoria', to: "matriculas#tipo_teoria"
    end
  end
  get 'matricula_nova', to: "matriculas#new"
  get 'reimprimir_contratos', to: "matriculas#reimprimir_contratos"
  get 'matricula_extra', to: "matriculas#new"
  get 'matriculas_encerradas', to: "matriculas#encerradas"
  get 'altera_encerramento', to: "matriculas#altera_encerramento"
  post 'refaz_contrato', to: "matriculas#refaz_contrato"
  get 'rematricular', to: "matriculas#rematricular"
  get 'rematricular_base', to: "matriculas#rematricular_base"
  get 'reativar_matricula/:id', to: "matriculas#reativar_matricula", as: :reativar_matricula

  #professores
  get 'professores_inativos', to: "professores#inativos"
  get 'professor/:id/controlar_horarios' => 'professores#controlar_horarios', as: :controlar_horarios
  get 'professor/:id/listar_alunos' => 'professores#listar_alunos', as: :listar_alunos
  get 'professor/:horario_id/alunos_horario' => 'professores#alunos_horario', as: :alunos_horario
  get 'alterna_professor/:id', to: "professores#alterna_professor", as: :alterna_professor

  #salarios
  get 'atribuir_salarios', to: "salarios#atribuir_salarios"
  get 'salarios/:professor_id/visualizar_salarios', to: 'salarios#visualizar_salarios', as: :visualizar_salarios

end

app/controllers/professores_controller.rb
# encoding: UTF-8
class ProfessoresController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy, :controlar_horarios, :listar_alunos, :alterna_professor]

  def index
    @professores_total = Professor.where(ativo: true)
    @pagy, @professores = pagy(@professores_total.order(:id))
  end

  def show
  end

  def new
    @professor = Professor.new
  end

  def edit
  end

  def create
    @professor = Professor.new(professor_params)
    @professor.ativo = true
    respond_to do |format|
      if @professor.save
        #gera_notificacao("admin",@professor, action_name)
        format.html { redirect_to @professor, notice: "professor #{@professor.nome} criado com sucesso." }
        #format.json { render action: 'show', status: :created, location: @professor }
      else
        showErrors(@professor.errors)
        format.html { render action: 'new' }
        #format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @professor.update(professor_params)
        #gera_notificacao("admin",@professor, action_name)
        format.html { redirect_to @professor, notice: "Dados do professor #{@professor.nome} foram atualizados com sucesso." }
        #format.json { head :no_content }
      else
        showErrors(@professor.errors)
        format.html { render action: 'edit' }
        #format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    respond_to do |format|
      if @professor.destroy
        #gera_notificacao("admin",@professor, action_name)
        format.html { redirect_to professores_path}
        #format.json { head :no_content }
      else
        showErrors(@professor.errors)
        format.html { redirect_back fallback_location: professores_path }
      end
    end
  end

  def alterna_professor
    if @professor.ativo?
      tem_aluno = false
      @professor.horarios.each do |horario|
        horario.matriculas.size > 0 ? tem_aluno = true : tem_aluno = false
      end
      if tem_aluno
        redirect_to professores_path, alert: "Exclusão cancelada. O professor #{@professor.nome} tem alunos vinculados. Favor alterar a matricula dos alunos."
        return
      else  
        @professor.update_attribute(:ativo, false)
        @professor.horarios.destroy_all
      end
    else
      @professor.update_attribute(:ativo, true)
    end
    redirect_to professores_inativos_path, notice: "Status do professor #{@professor.nome} alterado com sucesso."
  end

  def inativos
    @inativos = Professor.where(ativo: false)
    @pagy, @professores = pagy(@inativos.order(:id))
  end

  def controlar_horarios
    @pagy, @horarios = pagy(@professor.horarios.order('dia','horario'))
  end

  def listar_alunos
    @horarios = @professor.horarios.order('dia','horario').joins(:matriculas).group('horarios.id')#.page(params[:page]).per_page(9)
  end

  def alunos_horario
    @horario = Horario.find(params[:horario_id])
    @aulas = @horario.aulas
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:nome, :endereco, :rg, :cpf, :telefone, :celular, :email, :nascimento, :bairro, :cidade,
        :uf, :cep, :pai, :mae, :nacionalidade, :profissao, :escolaridade)
    end
end

app/helpers/professores_helper.rb
module ProfessoresHelper
end

app/views/professores/_form.html.erb
<div class="container">
  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-12">
          <div class="p-5">
            <%= form_with model: @professor, local: true, class: "user" do |f| %>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nome', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'CPF', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :nome, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :cpf, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Endereço', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 text-center">
                  <%= f.label 'Bairro', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :endereco, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :bairro, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Cidade', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Estado', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6  mb-3 mb-sm-0">
                  <%= f.text_field :cidade, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :uf, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'CEP', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Email', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">            
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :cep, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :email, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Telefone', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Celular', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :telefone, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :celular, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'RG', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Data de Nascimento', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :rg, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <% if action_name != "edit" %>
                    <%= f.text_field :nascimento, class: "form-control" %>
                  <% else %>
                    <%= f.text_field :nascimento, class: "form-control", value: @professor.nascimento.datePTBR %>
                  <% end %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nacionalidade', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nome do Pai', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :nacionalidade, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :pai, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nome da Mãe', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Profissão', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :mae, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :profissao, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Escolaridade', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Valor da Aula', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :escolaridade, class: "form-control" %>
                </div>
              </div>
              <%= f.submit "Salvar", class: "btn btn-primary btn-user btn-block" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/professores/alunos_horario.html.erb
<div class="page-header">
  <h2>Professor <%= @horario.professor.nome %> - <%= "#{dia(@horario.dia)} - #{hora(@horario.horario)}" %></h2>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Curso</th>
      <th>Aluno</th>
    </tr>
  </thead>

  <tbody>
    <% @aulas.each do |aula| %>
      <tr>
        <% if aula.teoria %>
          <td>Teoria</td>
        <% elsif aula.musicalizacao %>
          <td>Musicalização Infantil</td>
        <% else %>
          <td><%= aula.matricula.curso.nome %></td>
        <% end %>
        <td><%= aula.matricula.aluno.nome %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= button_to 'Voltar', controlar_horarios_path(id: @horario.professor.id), :class => "btn btn-default", :method => :get  %>

app/views/professores/controlar_horarios.html.erb
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Ajustar Horários do Professor <%= @professor.nome %></h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Ações:</div>
        <%= link_to "Cadastrar novo horário", disponivel_path(professor_id: @professor.id), class: "dropdown-item" %>
        <%= link_to "Limpar horários", destroy_all_path(professor_id: @professor.id), { class: "dropdown-item", data: { confirm: "Tem certeza que deseja excluir todos os horários do #{@professor.nome}?" }} %>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Disponibilidade de Horários</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        <tr>
        <th>Dia</th>
          <th>Horário</th>
          <th>Nº Alunos</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @horarios.each do |horario| %>
          <tr>
            <td><%= dayPTBR(horario.dia) %></td>
            <td><%= "#{hourPTBR(horario.horario)} até #{hourPTBR(horario.horario+50*60)}" %></td>
            <td><%= link_to horario.matriculas.size, alunos_horario_path(horario_id: horario) %></a></td>
            <td><%= button_to 'Editar', edit_horario_path(horario), :class => "btn btn-primary btn-xs", :method => :get %></td>
            <td><%= button_to 'Excluir', horario, :class => "btn btn-primary btn-xs", :method => :delete, data: { confirm: "Tem certeza que deseja excluir a horario #{horario.horario}?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/professores/edit.html.erb
<%= render 'form' %>

app/views/professores/inativos.html.erb
<!-- Table -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= controller_name.capitalize %> Inativos <small>// Quantidade: <%= @inativos.size %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="userTable" width="100%" cellspacing="0">
        <thead>
          <tr role="row">
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 3%;">Nº</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 34%;">Nome</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 15%;">Telefone</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 15%;">Celular</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 33%;">Opções</th>
          </tr>
       </thead>

       <tbody>
       		<% @professores.each do |professor| %>
			      <tr>
              <td><%= professor.id %></td>
			        <td><%= professor.nome %></td>
			        <td><%= professor.telefone %></td>
			        <td><%= professor.celular %></td>
              <td>
                <%= link_to professor, :class => "btn btn-primary btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
                  <span class="text">Abrir</span>
                <% end %>
                <%= link_to edit_professor_path(professor), :class => "btn btn-warning btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-exclamation-triangle"></i></span>
                  <span class="text">Editar</span>
                <% end %>
                <%= link_to alterna_professor_path(professor), :class => "btn btn-danger btn-icon-split btn-sm", :method => :get, data: { confirm: "Tem certeza que deseja reativar o(a) #{controller_name.singularize} #{professor.nome}?" } do %>
                  <span class="icon text-white-50"><i class="fas fa-trash"></i></span>
                  <span class="text">Reativar</span>
                <% end %>
              </td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
    <%== pagy_bootstrap_nav(@pagy) %>
	</div>
</div>
<!-- End of Table -->

app/views/professores/index.html.erb
<!-- Table -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= controller_name.capitalize %> Cadastrados(as) <small>// Quantidade: <%= @professores_total.size %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="userTable" width="100%" cellspacing="0">
        <thead>
          <tr role="row">
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 3%;">Nº</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 34%;">Nome</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 15%;">Telefone</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 15%;">Celular</th>
            <th class="sorting_asc" rowspan="1" colspan="1" style="width: 33%;">Opções</th>
          </tr>
       </thead>

       <tbody>
       		<% @professores.each do |professor| %>
			      <tr>
              <td><%= professor.id %></td>
			        <td><%= professor.nome %></td>
			        <td><%= professor.telefone %></td>
			        <td><%= professor.celular %></td>
              <td>
                <%= link_to professor, :class => "btn btn-primary btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
                  <span class="text">Abrir</span>
                <% end %>
                <%= link_to edit_professor_path(professor), :class => "btn btn-warning btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-exclamation-triangle"></i></span>
                  <span class="text">Editar</span>
                <% end %>
                <%= link_to alterna_professor_path(professor), :class => "btn btn-danger btn-icon-split btn-sm", :method => :get, data: { confirm: "Tem certeza que deseja desativar o(a) #{controller_name.singularize} #{professor.nome}?" } do %>
                  <span class="icon text-white-50"><i class="fas fa-trash"></i></span>
                  <span class="text">Desativar</span>
                <% end %>
              </td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
    <%== pagy_bootstrap_nav(@pagy) %>
	</div>
</div>
<!-- End of Table -->

app/views/professores/listar_alunos.html.erb
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Lista de Alunos do Professor <%= @professor.nome %></h6>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Dia</th>
          <th>Horário</th>
          <th>Curso</th>
          <th>Aluno</th>
        </tr>
      </thead>

      <tbody>
        <% @horarios.each do |horario| %>
          <% horario.aulas.each do |aula| %>
            <tr>
              <td><%= dayPTBR(horario.dia) %>
              <td><%= "#{hourPTBR(horario.horario)} até #{hourPTBR(horario.horario+50*60)}" %></td>
              <% if aula.teoria %>
                <td>Teoria</td>
              <% elsif aula.musicalizacao %>
                <td>Musicalização Infantil</td>
              <% else %>
                <td><%= aula.matricula.curso.nome %></td>
              <% end %>
              <td><%= aula.matricula.aluno.nome %></td>
              <td><%= button_to 'Abrir Ficha Matricula', aula.matricula, :class => "btn btn-primary btn-xs", :method => :get  %></td>
              <td><%= button_to 'Editar Matricula', edit_matricula_path(aula.matricula), :class => "btn btn-primary btn-xs", :method => :get  %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/professores/new.html.erb
<%= render 'form' %>

app/views/professores/show.erb
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary"><%= @professor.nome %> - Status: <u><%= @professor.ativo ? 'Ativo' : 'Inativo' %></u></h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Ações:</div>
        <%= link_to "Editar dados", edit_professor_path(@professor), class: "dropdown-item" %>
        <%= link_to "Alterar status", alterna_professor_path(@professor), { class: "dropdown-item", data: { confirm: "Tem certeza que deseja alterar o status do(a) #{controller_name.singularize} #{@professor.nome}?" }} %>
        <div class="dropdown-divider"></div>
        <%= link_to "Ajustar horários", controlar_horarios_path(id: @professor.id), class: "dropdown-item" %>
        <%= link_to "Consultar alunos vinculados", listar_alunos_path(id: @professor.id), class: "dropdown-item" %>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
  	<div class="form-group row">
  	<div class="col-sm-6 mb-3 mb-sm-0">
     	<ul class="list-group">
	      <li class="list-group-item"><b>professor nº:</b> <%= @professor.id %></li>
	      <li class="list-group-item"><b>Endereço:</b> <%= @professor.endereco %></li>
	      <li class="list-group-item"><b>Cidade:</b> <%= @professor.cidade %></li>
	      <li class="list-group-item"><b>CEP:</b> <%= @professor.cep %></li>
	      <li class="list-group-item"><b>Telefone:</b> <%= @professor.telefone %></li>
	      <li class="list-group-item"><b>RG:</b> <%= @professor.rg %></li>
	      <li class="list-group-item"><b>Nome da Mãe:</b> <%= @professor.mae %></li>
	      <li class="list-group-item"><b>Nacionalidade:</b> <%= @professor.nacionalidade %></li>
	      <li class="list-group-item"><b>Escolaridade:</b> <%= @professor.escolaridade %></li>
	    </ul>
	  </div>
	  <div class="col-sm-6">
	    <ul class="list-group">
	      <li class="list-group-item"><b>CPF:</b> <%= @professor.cpf %></li>
	      <li class="list-group-item"><b>Bairro:</b> <%= @professor.bairro %></li>
	      <li class="list-group-item"><b>Estado:</b> <%= @professor.uf %></li>
	      <li class="list-group-item"><b>E-mail:</b> <%= @professor.email %></li>
	      <li class="list-group-item"><b>Celular:</b> <%= @professor.celular %></li>
	      <li class="list-group-item"><b>Nascimento:</b> <%= @professor.nascimento.datePTBR %></li>
	      <li class="list-group-item"><b>Nome do Pai:</b> <%= @professor.pai %></li>
	      <li class="list-group-item"><b>Profissão:</b> <%= @professor.profissao %></li>
	      <li class="list-group-item"><b>Valor da Aula:</b> <%= number_to_currency(@professor.salarios.where(data_fim: nil).first.valor) %></li>
	    </ul>
	  </div>
	</div>

</div>