config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'user_sessions#new'

  resources :alunos, :circulares, :clientes, :cursos, :despesas, :horarios, :lecionam, :professores, :salarios, :tipificacoes, :users, :user_sessions

  #users and sessions
  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'
  get 'index' => 'user_sessions#index'
  get 'validate_user/:id', to: "users#validate_user", as: :validate_user

  #alunos
  get 'aluno/busca_dados_cliente', to: "alunos#busca_dados_cliente"
  get 'alunos_inativos', to: "alunos#inativos"
  get 'alterna_aluno/:id', to: "alunos#alterna_aluno", as: :alterna_aluno

  #circulares
  post 'circular_vigente', to: "circulares#circular_vigente"

  #clientes
	get 'alterna_cliente/:id', to: "clientes#alterna_cliente", as: :alterna_cliente
  get 'clientes_inativos', to: "clientes#inativos"
  get 'email_clientes', to: "clientes#listar_emails"

  #financas
  get 'visualiza_boletos', to: "financas#visualiza_boletos"
  get 'visualiza_folha', to: "financas#visualiza_folha"

  #horarios
  get 'horario/:professor_id/disponivel' => 'horarios#new', as: :disponivel
  get 'horario/:professor_id' => 'horarios#destroy_all',  as: :destroy_all

  #lecionam
  get 'lecionam/:curso_id/lecionar' => 'lecionam#new', as: :lecionar

  #matriculas
  resources :matriculas do
    collection do
      get 'busca_professores', to: "matriculas#busca_professores"
      get 'busca_horarios', to: "matriculas#busca_horarios"
      get 'busca_horarios_teoria', to: "matriculas#busca_horarios_teoria"
      get 'busca_dados_curso', to: "matriculas#busca_dados_curso"
      get 'tipo_teoria', to: "matriculas#tipo_teoria"
    end
  end
  get 'matricula_nova', to: "matriculas#new"
  get 'reimprimir_contratos', to: "matriculas#reimprimir_contratos"
  get 'matricula_extra', to: "matriculas#new"
  get 'matriculas_encerradas', to: "matriculas#encerradas"
  get 'altera_encerramento', to: "matriculas#altera_encerramento"
  post 'refaz_contrato', to: "matriculas#refaz_contrato"
  get 'rematricular', to: "matriculas#rematricular"
  get 'rematricular_base', to: "matriculas#rematricular_base"
  get 'reativar_matricula/:id', to: "matriculas#reativar_matricula", as: :reativar_matricula

  #professores
  get 'professores_inativos', to: "professores#inativos"
  get 'professor/:id/controlar_horarios' => 'professores#controlar_horarios', as: :controlar_horarios
  get 'professor/:id/listar_alunos' => 'professores#listar_alunos', as: :listar_alunos
  get 'professor/:horario_id/alunos_horario' => 'professores#alunos_horario', as: :alunos_horario
  get 'alterna_professor/:id', to: "professores#alterna_professor", as: :alterna_professor

  #salarios
  get 'atribuir_salarios', to: "salarios#atribuir_salarios"
  get 'salarios/:professor_id/visualizar_salarios', to: 'salarios#visualizar_salarios', as: :visualizar_salarios

end

app/controllers/circulares_controller.rb
# encoding: UTF-8
class CircularesController < ApplicationController
  before_action :set_circular, only: [:show, :edit, :update, :destroy, :circular_vigente]

  def index
    @circular_vigente = Circular.where(vigente: true).first
    @pagy, @circulares_inativas = pagy(Circular.where.not(id: @circular_vigente.id).order(id: :desc))
  end

  def show
  end

  def new
    @circular = Circular.new
  end

  def edit
  end

  def create
    @circular = Circular.new(circular_params)
    respond_to do |format|
      if @circular.save
        #gera_notificacao("admin",@circular, action_name)
        format.html { redirect_to @circular, notice: "Circular nº #{@circular.numero_circular} criado com sucesso." }
        #format.json { render action: 'show', status: :created, location: @circular }
      else
        showErrors(@circular.errors)
        format.html { render action: 'new' }
        #format.json { render json: @circular.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @circular.update(circular_params)
        #gera_notificacao("admin",@circular, action_name)
        format.html { redirect_to @circular, notice: "Dados da Circular nº #{@circular.numero_circular} foram atualizados com sucesso." }
        #format.json { head :no_content }
      else
        showErrors(@circular.errors)
        format.html { render action: 'edit' }
        #format.json { render json: @circular.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @circular.destroy
    #gera_notificacao("admin",@circular, action_name)
    respond_to do |format|
      format.html { redirect_to circulares_path}
      #format.json { head :no_content }
    end
  end

  def circular_vigente
    @circular_antiga = Circular.where(vigente: true).first
    if @circular_antiga && @circular_antiga.id != @circular.id
      @circular_antiga.update_attribute(:vigente, false)
    end
    respond_to do |format|
      if @circular.update_attribute(:vigente, true)
        format.html { redirect_to circulares_path, notice: "Circular nº #{@circular.numero_circular} foi definida como vigente." }
      else
        format.html { redirect_to circulares_path, alert: "Erro ao tentar definir a Circular nº #{@circular.numero_circular} como vigente." }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_circular
      @circular = Circular.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def circular_params
      params.require(:circular).permit(:numero_circular,:data_circular,:valor_mensalidade,:valor_extra,:valor_profissionalizante,
      :desconto,:vigente,:taxa_matricula,:salario_aula)
    end
end

app/helpers/circulares_helper.rb
module CircularesHelper
end

app/views/circulares/_form.html.erb
<div class="container">
  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-12">
          <div class="p-5">
            <%= form_with model: @circular, local: true, class: "user" do |f| %>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Nº da Circular', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Data da Circular', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :numero_circular, class: "form-control" %>
                </div>
                <div class="col-sm-6">
                  <%= f.text_field :data_circular, class: "form-control", value: (@circular.data_circular ? @circular.data_circular.datePTBR : '' ) %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Valor Mensal do Curso Básico', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Valor Mensal do Curso Extra', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :valor_mensalidade, class: "form-control" %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :valor_extra, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Valor Mensal do Curso de Canto Profissional', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Taxa de Matrícula', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :valor_profissionalizante, class: "form-control" %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :taxa_matricula, class: "form-control" %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Valor de Desconto', class: 'col-form-label-lg' %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0 text-center">
                  <%= f.label 'Salário Padrão por Aula', class: 'col-form-label-lg' %>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :desconto, class: "form-control" %>
                </div>
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <%= f.text_field :salario_aula, class: "form-control" %>
                </div>
              </div>
              <%= f.submit "Salvar", class: "btn btn-primary btn-user btn-block" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/circulares/edit.html.erb
<%= render 'form' %>

app/views/circulares/index.html.erb
<!-- Table -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= controller_name.capitalize %> Cadastrados(as) <small>// Vigente: <u>Circular nº <%= @circular_vigente.numero_circular %></u></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="userTable" width="100%" cellspacing="0">
        <thead>
          <tr role="row">
            <th class="sorting_asc" rowspan="1" colspan="1">Circular</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Data</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Curso Básico</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Curso Extra</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Taxa de Matrícula</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Salário por Aula</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Opções</th>
          </tr>
       </thead>

       <tbody>
          <tr>
            <td><%= @circular_vigente.numero_circular %></td>
            <td><%= I18n.l(@circular_vigente.data_circular) %></td>
            <td><%= number_to_currency(@circular_vigente.valor_mensalidade) %></td>
            <td><%= number_to_currency(@circular_vigente.valor_extra) %></td>
            <td><%= number_to_currency(@circular_vigente.taxa_matricula) %></td>
            <td><%= number_to_currency(@circular_vigente.salario_aula) %></td>
            <td>
              <%= link_to @circular_vigente, :class => "btn btn-primary btn-icon-split btn-sm", :method => :get do %>
                <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
                <span class="text">Visualizar</span>
              <% end %>
              <%= link_to edit_circular_path(@circular_vigente), :class => "btn btn-warning btn-icon-split btn-sm", :method => :get do %>
                <span class="icon text-white-50"><i class="fas fa-exclamation-triangle"></i></span>
                <span class="text">Editar</span>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered" id="userTable" width="100%" cellspacing="0">
        <thead>
          <tr role="row">
            <th class="sorting_asc" rowspan="1" colspan="1">Circular</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Data</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Curso Básico</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Curso Extra</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Taxa de Matrícula</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Salário por Aula</th>
            <th class="sorting_asc" rowspan="1" colspan="1">Opções</th>
          </tr>
       </thead>

       <tbody>
       		<% @circulares_inativas.each do |circular| %>
			      <tr>
              <td><%= circular.numero_circular %></td>
              <td><%= I18n.l(circular.data_circular) %></td>
              <td><%= number_to_currency(circular.valor_mensalidade) %></td>
              <td><%= number_to_currency(circular.valor_extra) %></td>
              <td><%= number_to_currency(circular.taxa_matricula) %></td>
              <td><%= number_to_currency(circular.salario_aula) %></td>
              <td>
                <%= link_to circular, :class => "btn btn-primary btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
                  <span class="text">Visualizar</span>
                <% end %>
                <%= link_to edit_circular_path(circular), :class => "btn btn-warning btn-icon-split btn-sm", :method => :get do %>
                  <span class="icon text-white-50"><i class="fas fa-exclamation-triangle"></i></span>
                  <span class="text">Editar</span>
                <% end %>
                <%= link_to circular_vigente_path(id: circular.id), :class => "btn btn-success btn-icon-split btn-sm", :method => :post do %>
                  <span class="icon text-white-50"><i class="fas fa-check"></i></span>
                  <span class="text">Ativar</span>
                <% end %>
              </td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
		</div>
    <%== pagy_bootstrap_nav(@pagy) %>
	</div>
</div>
<!-- End of Table -->

app/views/circulares/new.html.erb
<%= render 'form' %>

app/views/circulares/show.erb
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Circular nº <%= @circular.numero_circular %> - Status: <u><%= @circular.vigente ? "Vigente" : "Inativa" %></u></h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Ações:</div>
        <%= link_to "Editar dados", edit_circular_path(@circular), class: "dropdown-item" %>
        <%= link_to "Tornar Vigente", circular_vigente_path(id: @circular.id), { class: "dropdown-item", :method => :post } %>
      </div>
    </div>
  </div>

  <!-- Card Body -->
  <div class="card-body">
  	<div class="form-group row">
  	<div class="col-sm-6 mb-3 mb-sm-0">
     	<ul class="list-group">
	      <li class="list-group-item"><b>Data da Circular:</b> <%= I18n.l(@circular.data_circular) %></li>
        <li class="list-group-item"><b>Custo Anual do Curso Básico:</b> <%= number_to_currency(@circular.valor_mensalidade*12) %></li>
        <li class="list-group-item"><b>Custo Anual do Instrumento Extra:</b> <%= number_to_currency(@circular.valor_extra*12) %></li>
        <li class="list-group-item"><b>Custo Anual do Curso de Canto Profissional:</b> <%= number_to_currency(@circular.valor_profissionalizante*12) %></li>
        <li class="list-group-item"><b>Valor do Desconto:</b> <%= number_to_currency(@circular.desconto) %> (<%= (@circular.desconto / @circular.valor_mensalidade * 100).to_i %>%)</li>
	    </ul>
	  </div>
	  <div class="col-sm-6">
	    <ul class="list-group">
	      <li class="list-group-item"><b>Mensalidade do Curso Básico:</b> <%= number_to_currency(@circular.valor_mensalidade) %></li>
        <li class="list-group-item"><b>Mensalidade do Instrumento Extra:</b> <%= number_to_currency(@circular.valor_extra) %></li>
        <li class="list-group-item"><b>Mensalidade do Curso de Canto Profissional</b> <%= number_to_currency(@circular.valor_profissionalizante) %></li>
        <li class="list-group-item"><b>Taxa de Matrícula:</b> <%= number_to_currency(@circular.taxa_matricula) %></li>
        <li class="list-group-item"><b>Salário Padrão por Aula:</b> <%= number_to_currency(@circular.salario_aula) %></li>
	    </ul>
	  </div>
	</div>

</div>